name: convert-html
run-name: Convert our markdown articles to HTML.
on: [push]
jobs:
    convert-html:
      if: github.actor != 'github-actions[bot]'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Install Pandoc
          run: sudo apt-get update && sudo apt-get install -y pandoc

        - name: Convert MD to HTML
          run: bash scripts/convert_html.sh

        - name: Update the repo with my HTML files
          run: |
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add articles/*.html
            git diff --staged --quiet || git commit -m "Build: update HTML [skip ci]"
            git push
